name: Build and create version tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            extension: ".zip"
            runtime: "win-x64"
          - os: ubuntu-latest
            extension: ".tar.gz"
            runtime: "linux-x64"
          - os: macos-latest
            runtime: "osx-x64"
            extension: ".zip"
        node_version: [18]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      PROJECT_NAME: "Angor"
      SOLUTION_PATH: "src/Angor.sln"
      PROJECT_PATH: "src/Angor/Server/Angor.Server.csproj"
      BUILD_CONFIGURATION: "Release"

    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
      - name: Setup Node.js (${{ matrix.node_version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Variables
        run: |
          echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
        shell: bash

      - name: Workload
        run: dotnet workload restore ${{env.SOLUTION_PATH}}

      - name: Restore
        run: dotnet restore ${{env.SOLUTION_PATH}}

      - name: Unit Test
        run: dotnet test -v=normal -c ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_PATH}}

      - name: Check for changes in Directory.Build.props
        if: matrix.os == 'ubuntu-latest'
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^Directory.Build.props$'; then
            echo "File Directory.Build.props has changed."
            echo "::set-output name=changed::true"
          else
            echo "File Directory.Build.props has not changed."
            echo "::set-output name=changed::false"
          fi

      - name: Create tag
        if: steps.check_changes.outputs.changed == 'true'
        env:
          TAG_NAME: "v${{env.VERSION}}"
        run: |
          #git config --global user.name "${{ github.actor }}"
          #git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME